#ifndef CONSTANTS_H
#define CONSTANTS_H

#define HOURS_PER_DAY 24
#define DAYS_PER_WEEK 7

#define NUM_IMAGES 11

#define PATCH_LENGTH 30
#define PATCH_AREA (PATCH_LENGTH * PATCH_LENGTH)

//TODO find out if there is a better name for this...
#define THETA 1.072

enum {STOCK_MACRO, STOCK_PHYTO, STOCK_HERBIVORE, STOCK_WATERDECOMP,
      STOCK_SEDDECOMP, STOCK_SEDCONSUMER, STOCK_CONSUMER, STOCK_DOC, STOCK_POC,
      STOCK_DETRITUS, STOCK_ALL_CARBON};


#endif // CONSTANTS_H
